GET http://localhost:3333/courses

###

GET http://localhost:3333/courses/5ded0310-ffa6-4e0d-85f4-9cddbeb56163
###

POST http://localhost:3333/courses
Content-Type: application/json

{
    "title": "Curso Teste Zod"
}